# Generated by Django 3.2.5 on 2021-07-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='maximo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='minimo',
            field=models.IntegerField(null=True),
        ),
    ]
