# Generated by Django 3.2.5 on 2021-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20210706_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
